name: MySQLInventoryManagement
main: main.java.me.avankziar.mim.spigot.MIM
version: 1
author: Avankziar
api-version: 1.19
softdepend: [InterfaceHub]
description: A Mysql Inventory synchronization and Custom Inventory management.